### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by Pandapip1** [ros2-rust/cargo-ament-build#18]
See https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control

**Comment by luca-della-vedova** [comment]
I'm a bit on the fence on this and erring on the side of not adding a lockfile for two main reasons:

* The package itself and its dependencies are fairly straightforward, the risk of minor versions breaking it is small enough that it might not be worth dropping automatic security updates / bugfixes and maintaining the lockfile.
* The main way this package is used is through `cargo install` that by default ignores the lockfile anyway unless the `--locked` flag is specified.

Happy to hear otherwise though

**Comment by Pandapip1** [comment]
Sounds good to me.
